name: RepoGuardianBot Scan1

on:
  pull_request:
    branches:
      - main
      
jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run RepoGuardianBot
        run: |
          python bot.py

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: scan-reports
          path: repo_guardian_bot/reports/
